## docker-compose configuration file for apache static web server
## 
## you configure this service you must edit .env file.
##

version: '3.3'

services:
  web:
    image: httpd:latest
    volumes:
      - ./www:/usr/local/apache2/htdocs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${ROUTERNAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${ROUTERNAME}.entrypoints=websecure"
      - "traefik.http.routers.${ROUTERNAME}.tls.certresolver=myresolver"
    networks:
      - traefik_network
#    ports:
#      - "80:80"

  ssh:
    image: panubo/sshd
    volumes:
      - ./www:/home/admin
      - ./keys:/etc/ssh/keys
      - ./authorized_keys:/etc/authorized_keys/admin
    environment:
      - SSH_USERS=admin:1000:1000
    ports:
      - ${SSH_PORT}:22


networks:
  traefik_network:
    external:
      name: traefik_default
